cmake_minimum_required(VERSION 3.14)
project(kvrocks)

set(CMAKE_CXX_STANDARD 14)

include_directories(src)
include_directories(src/cli)
include_directories(src/cluster)
include_directories(src/commands)
include_directories(src/common)
include_directories(src/config)
include_directories(src/search)
include_directories(src/search/executors)
include_directories(src/search/passes)
include_directories(src/server)
include_directories(src/stats)
include_directories(src/storage)
include_directories(src/storage/rdb)
include_directories(src/types)
include_directories(src/vendor)
include_directories(tests/cppunit)
include_directories(utils/kvrocks2redis)

add_executable(kvrocks
        cmake/checks/static_libstdcxx.cc
        src/cli/daemon_util.h
        src/cli/main.cc
        src/cli/pid_util.h
        src/cli/signal_util.h
        src/cli/version_util.h
        src/cluster/batch_sender.cc
        src/cluster/batch_sender.h
        src/cluster/cluster.cc
        src/cluster/cluster.h
        src/cluster/cluster_defs.h
        src/cluster/redis_slot.cc
        src/cluster/redis_slot.h
        src/cluster/replication.cc
        src/cluster/replication.h
        src/cluster/slot_import.cc
        src/cluster/slot_import.h
        src/cluster/slot_migrate.cc
        src/cluster/slot_migrate.h
        src/cluster/sync_migrate_context.cc
        src/cluster/sync_migrate_context.h
        src/commands/blocking_commander.h
        src/commands/cmd_bit.cc
        src/commands/cmd_bloom_filter.cc
        src/commands/cmd_cluster.cc
        src/commands/cmd_function.cc
        src/commands/cmd_geo.cc
        src/commands/cmd_hash.cc
        src/commands/cmd_hll.cc
        src/commands/cmd_json.cc
        src/commands/cmd_key.cc
        src/commands/cmd_list.cc
        src/commands/cmd_pubsub.cc
        src/commands/cmd_replication.cc
        src/commands/cmd_script.cc
        src/commands/cmd_search.cc
        src/commands/cmd_server.cc
        src/commands/cmd_set.cc
        src/commands/cmd_sortedint.cc
        src/commands/cmd_stream.cc
        src/commands/cmd_string.cc
        src/commands/cmd_txn.cc
        src/commands/cmd_zset.cc
        src/commands/command_parser.h
        src/commands/commander.cc
        src/commands/commander.h
        src/commands/error_constants.h
        src/commands/scan_base.h
        src/commands/ttl_util.h
        src/common/bit_util.h
        src/common/bitfield_util.cc
        src/common/bitfield_util.h
        src/common/cron.cc
        src/common/cron.h
        src/common/db_util.h
        src/common/encoding.cc
        src/common/encoding.h
        src/common/event_util.h
        src/common/io_util.cc
        src/common/io_util.h
        src/common/lock_manager.h
        src/common/observer_or_unique.h
        src/common/parse_util.cc
        src/common/parse_util.h
        src/common/port.h
        src/common/range_spec.cc
        src/common/range_spec.h
        src/common/rdb_stream.cc
        src/common/rdb_stream.h
        src/common/rocksdb_crc32c.h
        src/common/scope_exit.h
        src/common/status.h
        src/common/string_util.cc
        src/common/string_util.h
        src/common/task_runner.cc
        src/common/task_runner.h
        src/common/thread_util.cc
        src/common/thread_util.h
        src/common/time_util.h
        src/common/type_util.h
        src/common/unique_fd.h
        src/config/config.cc
        src/config/config.h
        src/config/config_type.h
        src/config/config_util.cc
        src/config/config_util.h
        src/search/executors/filter_executor.h
        src/search/executors/full_index_scan_executor.h
        src/search/executors/hnsw_vector_field_knn_scan_executor.h
        src/search/executors/hnsw_vector_field_range_scan_executor.h
        src/search/executors/limit_executor.h
        src/search/executors/merge_executor.h
        src/search/executors/mock_executor.h
        src/search/executors/noop_executor.h
        src/search/executors/numeric_field_scan_executor.h
        src/search/executors/projection_executor.h
        src/search/executors/sort_executor.h
        src/search/executors/tag_field_scan_executor.h
        src/search/executors/topn_sort_executor.h
        src/search/passes/cost_model.h
        src/search/passes/index_selection.h
        src/search/passes/interval_analysis.h
        src/search/passes/lower_to_plan.h
        src/search/passes/manager.h
        src/search/passes/push_down_not_expr.h
        src/search/passes/recorder.h
        src/search/passes/simplify_and_or_expr.h
        src/search/passes/simplify_boolean.h
        src/search/passes/sort_limit_fuse.h
        src/search/passes/sort_limit_to_knn.h
        src/search/common_parser.h
        src/search/common_transformer.h
        src/search/hnsw_indexer.cc
        src/search/hnsw_indexer.h
        src/search/index_info.h
        src/search/index_manager.cc
        src/search/index_manager.h
        src/search/indexer.cc
        src/search/indexer.h
        src/search/interval.h
        src/search/ir.h
        src/search/ir_dot_dumper.h
        src/search/ir_iterator.h
        src/search/ir_pass.h
        src/search/ir_plan.h
        src/search/ir_sema_checker.h
        src/search/plan_executor.cc
        src/search/plan_executor.h
        src/search/redis_query_parser.h
        src/search/redis_query_transformer.h
        src/search/search_encoding.h
        src/search/sql_parser.h
        src/search/sql_transformer.h
        src/search/value.h
        src/server/namespace.cc
        src/server/namespace.h
        src/server/redis_connection.cc
        src/server/redis_connection.h
        src/server/redis_reply.cc
        src/server/redis_reply.h
        src/server/redis_request.cc
        src/server/redis_request.h
        src/server/server.cc
        src/server/server.h
        src/server/tls_util.cc
        src/server/tls_util.h
        src/server/worker.cc
        src/server/worker.h
        src/stats/disk_stats.cc
        src/stats/disk_stats.h
        src/stats/log_collector.cc
        src/stats/log_collector.h
        src/stats/stats.cc
        src/stats/stats.h
        src/storage/rdb/rdb.cc
        src/storage/rdb/rdb.h
        src/storage/rdb/rdb_intset.cc
        src/storage/rdb/rdb_intset.h
        src/storage/rdb/rdb_listpack.cc
        src/storage/rdb/rdb_listpack.h
        src/storage/rdb/rdb_ziplist.cc
        src/storage/rdb/rdb_ziplist.h
        src/storage/rdb/rdb_zipmap.cc
        src/storage/rdb/rdb_zipmap.h
        src/storage/batch_debugger.h
        src/storage/batch_extractor.cc
        src/storage/batch_extractor.h
        src/storage/batch_indexer.h
        src/storage/compact_filter.cc
        src/storage/compact_filter.h
        src/storage/compaction_checker.cc
        src/storage/compaction_checker.h
        src/storage/event_listener.cc
        src/storage/event_listener.h
        src/storage/iterator.cc
        src/storage/iterator.h
        src/storage/redis_db.cc
        src/storage/redis_db.h
        src/storage/redis_metadata.cc
        src/storage/redis_metadata.h
        src/storage/redis_pubsub.cc
        src/storage/redis_pubsub.h
        src/storage/scripting.cc
        src/storage/scripting.h
        src/storage/storage.cc
        src/storage/storage.h
        src/storage/table_properties_collector.cc
        src/storage/table_properties_collector.h
        src/types/bloom_filter.cc
        src/types/bloom_filter.h
        src/types/geohash.cc
        src/types/geohash.h
        src/types/hyperloglog.cc
        src/types/hyperloglog.h
        src/types/json.h
        src/types/redis_bitmap.cc
        src/types/redis_bitmap.h
        src/types/redis_bitmap_string.cc
        src/types/redis_bitmap_string.h
        src/types/redis_bloom_chain.cc
        src/types/redis_bloom_chain.h
        src/types/redis_geo.cc
        src/types/redis_geo.h
        src/types/redis_hash.cc
        src/types/redis_hash.h
        src/types/redis_hyperloglog.cc
        src/types/redis_hyperloglog.h
        src/types/redis_json.cc
        src/types/redis_json.h
        src/types/redis_list.cc
        src/types/redis_list.h
        src/types/redis_set.cc
        src/types/redis_set.h
        src/types/redis_sortedint.cc
        src/types/redis_sortedint.h
        src/types/redis_stream.cc
        src/types/redis_stream.h
        src/types/redis_stream_base.cc
        src/types/redis_stream_base.h
        src/types/redis_string.cc
        src/types/redis_string.h
        src/types/redis_zset.cc
        src/types/redis_zset.h
        src/types/sample_helper.h
        src/vendor/crc64.cc
        src/vendor/crc64.h
        src/vendor/endianconv.cc
        src/vendor/endianconv.h
        src/vendor/lzf.cc
        src/vendor/lzf.h
        src/vendor/murmurhash2.h
        src/vendor/rand.cc
        src/vendor/rand.h
        src/vendor/sha1.cc
        src/vendor/sha1.h
        tests/cppunit/types/bitmap_test.cc
        tests/cppunit/types/bloom_chain_test.cc
        tests/cppunit/types/bloom_filter_test.cc
        tests/cppunit/types/geo_test.cc
        tests/cppunit/types/hash_test.cc
        tests/cppunit/types/hyperloglog_test.cc
        tests/cppunit/types/json_test.cc
        tests/cppunit/types/list_test.cc
        tests/cppunit/types/set_test.cc
        tests/cppunit/types/sortedint_test.cc
        tests/cppunit/types/stream_test.cc
        tests/cppunit/types/string_test.cc
        tests/cppunit/types/zset_test.cc
        tests/cppunit/bitfield_util_test.cc
        tests/cppunit/cluster_test.cc
        tests/cppunit/command_parser_test.cc
        tests/cppunit/compact_test.cc
        tests/cppunit/config_test.cc
        tests/cppunit/cron_test.cc
        tests/cppunit/disk_test.cc
        tests/cppunit/encoding_test.cc
        tests/cppunit/hnsw_index_test.cc
        tests/cppunit/hnsw_node_test.cc
        tests/cppunit/indexer_test.cc
        tests/cppunit/interval_test.cc
        tests/cppunit/io_util_test.cc
        tests/cppunit/ir_dot_dumper_test.cc
        tests/cppunit/ir_pass_test.cc
        tests/cppunit/ir_sema_checker_test.cc
        tests/cppunit/iterator_test.cc
        tests/cppunit/log_collector_test.cc
        tests/cppunit/main.cc
        tests/cppunit/metadata_test.cc
        tests/cppunit/namespace_test.cc
        tests/cppunit/observer_or_unique_test.cc
        tests/cppunit/parse_util.cc
        tests/cppunit/plan_executor_test.cc
        tests/cppunit/rdb_stream_test.cc
        tests/cppunit/rdb_test.cc
        tests/cppunit/rdb_util.h
        tests/cppunit/redis_query_parser_test.cc
        tests/cppunit/sql_parser_test.cc
        tests/cppunit/status_test.cc
        tests/cppunit/storage_test.cc
        tests/cppunit/string_reply_test.cc
        tests/cppunit/string_util_test.cc
        tests/cppunit/task_runner_test.cc
        tests/cppunit/test_base.h
        tests/cppunit/writebatch_indexer_test.cc
        utils/kvrocks2redis/config.cc
        utils/kvrocks2redis/config.h
        utils/kvrocks2redis/main.cc
        utils/kvrocks2redis/parser.cc
        utils/kvrocks2redis/parser.h
        utils/kvrocks2redis/redis_writer.cc
        utils/kvrocks2redis/redis_writer.h
        utils/kvrocks2redis/sync.cc
        utils/kvrocks2redis/sync.h
        utils/kvrocks2redis/writer.cc
        utils/kvrocks2redis/writer.h)
